/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_integrador1.votantes;

import com.mycompany.proyecto_integrador1.Sistema.AdminInterface;
import com.mycompany.proyecto_integrador1.Sistema.CandidateForm;
import com.mycompany.proyecto_integrador1.Sistema.RegistrarVotantes;

/**
 *
 * @author Nicol Alejandra
 */
public class VotarPersonero extends javax.swing.JFrame {

    /**
     * Creates new form VotarPersonero
     */
    public VotarPersonero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearCandidatos = new javax.swing.JButton();
        btnRegistrarVotantes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarVotantes1 = new javax.swing.JButton();
        btnRegistrarVotantes2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarVotantes3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1562, 850));
        jPanel1.setPreferredSize(new java.awt.Dimension(1845, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearCandidatos.setBackground(new java.awt.Color(58, 134, 255));
        btnCrearCandidatos.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        btnCrearCandidatos.setText("PERSONERO");
        btnCrearCandidatos.setToolTipText("");
        btnCrearCandidatos.setBorder(null);
        btnCrearCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCandidatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 350, 80));

        btnRegistrarVotantes.setBackground(new java.awt.Color(65, 90, 119));
        btnRegistrarVotantes.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        btnRegistrarVotantes.setText("Registrar Voto");
        btnRegistrarVotantes.setBorder(null);
        btnRegistrarVotantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVotantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVotantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 340, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 660, -1));

        jPanel3.setBackground(new java.awt.Color(230, 243, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_Segundario.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 530, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_atras.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1860, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_azul_claro_Gramde.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 1340, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_azul_oscuro_GRANDE_2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, 120));

        btnRegistrarVotantes1.setBackground(new java.awt.Color(65, 90, 119));
        btnRegistrarVotantes1.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        btnRegistrarVotantes1.setText("Registrar Voto");
        btnRegistrarVotantes1.setBorder(null);
        btnRegistrarVotantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVotantes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVotantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 340, 80));

        btnRegistrarVotantes2.setBackground(new java.awt.Color(65, 90, 119));
        btnRegistrarVotantes2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        btnRegistrarVotantes2.setText("Siguiente");
        btnRegistrarVotantes2.setBorder(null);
        btnRegistrarVotantes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVotantes2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVotantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 340, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_azul_oscuro_GRANDE_2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, 120));

        btnRegistrarVotantes3.setBackground(new java.awt.Color(65, 90, 119));
        btnRegistrarVotantes3.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        btnRegistrarVotantes3.setText("Registrar Voto");
        btnRegistrarVotantes3.setBorder(null);
        btnRegistrarVotantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVotantes3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVotantes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 340, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1562, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVotantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVotantesActionPerformed

        javax.swing.JOptionPane.showMessageDialog(this, "Funcionalidad para registrar votantes");

        RegistrarVotantes registrovotantes = new RegistrarVotantes();
        registrovotantes.setVisible(true);

    }//GEN-LAST:event_btnRegistrarVotantesActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AdminInterface admi = new AdminInterface();
        admi.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnCrearCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCandidatosActionPerformed

        CandidateForm candidateForm = new CandidateForm();
        candidateForm.setVisible(true);
    }//GEN-LAST:event_btnCrearCandidatosActionPerformed

    private void btnRegistrarVotantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVotantes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVotantes1ActionPerformed

    private void btnRegistrarVotantes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVotantes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVotantes2ActionPerformed

    private void btnRegistrarVotantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVotantes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVotantes3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotarPersonero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotarPersonero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotarPersonero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotarPersonero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotarPersonero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCandidatos;
    private javax.swing.JButton btnRegistrarVotantes;
    private javax.swing.JButton btnRegistrarVotantes1;
    private javax.swing.JButton btnRegistrarVotantes2;
    private javax.swing.JButton btnRegistrarVotantes3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
